DROP VIEW EMPLOYEESVIEW;

CREATE FORCE VIEW PUBLIC.EMPLOYEESVIEW(NAME, AGE, POSITION, DEPARTMENT) AS
SELECT
    EMPLOYEES.NAME,
    AGE,
    POSITIONS.NAME AS POSITION,
    DEPARTMENTS.NAME AS DEPARTMENT
FROM PUBLIC.DEPTSTAFF
INNER JOIN PUBLIC.DEPARTMENTS
    ON 1=1
INNER JOIN PUBLIC.EMPLOYEES
    ON 1=1
INNER JOIN PUBLIC.POSITIONS
    ON 1=1
WHERE (EMPLOYEES.POSITIONID = POSITIONS.ID)
    AND ((EMPLOYEES.ID = DEPTSTAFF.EMPLOYEEID)
    AND (DEPARTMENTS.ID = DEPTSTAFF.DEPARTMENTID));
